name: Upload Cassandra Tarball

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download Cassandra tarball
        run: |
          wget https://downloads.apache.org/cassandra/4.1.3/apache-cassandra-4.1.3-bin.tar.gz -O cassandra.tar.gz

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-launchpadlib

      - name: Upload to Launchpad (dry-run example)
        env:
          LP_CREDENTIALS: ${{ secrets.LAUNCHPAD_CREDS }}
        run: |
          mkdir ~/.cache
          echo "$LP_CREDENTIALS" > ~/.cache/lp-creds
          chmod 600 ~/.cache/lp-creds

          cat > upload.py <<EOF
import launchpadlib.launchpad
lp = launchpadlib.launchpad.Launchpad.login_with('Cassandra Uploader', 'production', version='devel', credentials_file='~/.cache/lp-creds')
project = lp.projects['cassandra-releases']
project.add_attachment(open('cassandra.tar.gz', 'rb'), 'cassandra-4.1.3.tar.gz', 'application/gzip')
EOF

          python3 upload.py
