name: Upload Cassandra Tarball

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download Cassandra tarball
        run: |
          wget https://downloads.apache.org/cassandra/4.1.3/apache-cassandra-4.1.3-bin.tar.gz -O cassandra.tar.gz

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-launchpadlib

      - name: Upload to Launchpad
        env:
          LP_CREDENTIALS: ${{ secrets.LAUNCHPAD_CREDS }}
        run: |
          mkdir -p ~/.cache
          echo "$LP_CREDENTIALS" > ~/.cache/lp-creds
          chmod 600 ~/.cache/lp-creds
      
          python3 scripts/upload_to_launchpad.py